version: "2"

services:
  DATEX-PLAYGROUND:
  
    container_name: ${UNYT_NAME}
    image: denoland/deno

    ports:
      - ${UNYT_INTERNAL_PORT}:80
    expose:
      - ${UNYT_INTERNAL_PORT}
    networks:
      - main
    working_dir: /app
    volumes:
      - ../:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${UNYT_NAME}.rule=Host(`${UNYT_HOST}`)"
      - "traefik.http.routers.${UNYT_NAME}.entrypoints=web"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${UNYT_NAME}.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.${UNYT_NAME}-secured.rule=Host(`${UNYT_HOST}`)"
      - "traefik.http.routers.${UNYT_NAME}-secured.tls=true"
      - "traefik.http.routers.${UNYT_NAME}-secured.tls.certresolver=myhttpchallenge"
    command: 
      - /bin/sh
      - -c
      - |
          rm deno.lock
          deno cache --reload -q ./backend/entrypoint.ts
          deno run -A -q https://dev.cdn.unyt.org/uix/run.ts --reload -w -v
    restart: on-failure

networks:
  main:
    external: true
